# Generated by Django 4.1 on 2022-09-30 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoderBlog', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 9, 30)),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_blogs'),
        ),
    ]
