# Generated by Django 4.1 on 2022-09-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0005_blog_autor_blog_fecha_blog_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
